const products = [
  { productID: 11, productName: "Queso Cabrales", unitPrice: 21.0 },
  { productID: 12, productName: "Queso Manchego La Pastora", unitPrice: 38.0 },
  { productID: 13, productName: "Konbu", unitPrice: 6.0 },
  { productID: 14, productName: "Tofu", unitPrice: 23.25 },
  { productID: 15, productName: "Genen Shouyu", unitPrice: 15.5 },
  { productID: 16, productName: "Pavlova", unitPrice: 17.45 },
  { productID: 17, productName: "Alice Mutton", unitPrice: 39.0 },
  { productID: 18, productName: "Carnarvon Tigers", unitPrice: 62.5 },
  { productID: 19, productName: "Teatime Chocolate Biscuits", unitPrice: 9.2 },
  { productID: 20, productName: "Sir Rodney's Marmalade", unitPrice: 81.0 },
  { productID: 21, productName: "Sir Rodney's Scones", unitPrice: 10.0 },
  { productID: 22, productName: "Gustaf's Knäckebröd", unitPrice: 21.0 },
  { productID: 23, productName: "Tunnbröd", unitPrice: 9.0 },
  { productID: 24, productName: "Guaraná Fantástica", unitPrice: 4.5 },
  { productID: 25, productName: "NuNuCa Nuß-Nougat-Creme", unitPrice: 14.0 },
  { productID: 26, productName: "Gumbär Gummibärchen", unitPrice: 31.23 },
  { productID: 27, productName: "Schoggi Schokolade", unitPrice: 43.9 },
  { productID: 28, productName: "Rössle Sauerkraut", unitPrice: 45.6 },
  { productID: 29, productName: "Thüringer Rostbratwurst", unitPrice: 123.79 },
  { productID: 30, productName: "Nord-Ost Matjeshering", unitPrice: 25.89 },
  { productID: 31, productName: "Gorgonzola Telino", unitPrice: 12.5 },
  { productID: 32, productName: "Mascarpone Fabioli", unitPrice: 32.0 },
  { productID: 33, productName: "Geitost", unitPrice: 2.5 },
  { productID: 34, productName: "Sasquatch Ale", unitPrice: 14.0 },
  { productID: 35, productName: "Steeleye Stout", unitPrice: 18.0 },
  { productID: 36, productName: "Inlagd Sill", unitPrice: 19.0 },
  { productID: 37, productName: "Gravad lax", unitPrice: 26.0 },
  { productID: 38, productName: "Côte de Blaye", unitPrice: 263.5 },
  { productID: 39, productName: "Chartreuse verte", unitPrice: 18.0 },
  { productID: 40, productName: "Boston Crab Meat", unitPrice: 18.4 },
  { productID: 41, productName: "Jack's New England Clam Chowder", unitPrice: 9.65 },
  { productID: 42, productName: "Singaporean Hokkien Fried Mee", unitPrice: 14.0 },
  { productID: 43, productName: "Ipoh Coffee", unitPrice: 46.0 },
  { productID: 44, productName: "Gula Malacca", unitPrice: 19.45 },
  { productID: 45, productName: "Rogede sild", unitPrice: 9.5 },
  { productID: 46, productName: "Spegesild", unitPrice: 12.0 },
  { productID: 47, productName: "Zaanse koeken", unitPrice: 9.5 },
  { productID: 48, productName: "Chocolade", unitPrice: 12.75 },
  { productID: 49, productName: "Maxilaku", unitPrice: 20.0 },
];

export default products;